
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { analyzeResumeAgainstJobDescription } from '../services/geminiService';
import type { Job, ResumeAnalysisResult } from '../types';
import Spinner from './Spinner';
import { SparklesIcon, DocumentDuplicateIcon, PrinterIcon, DocumentArrowDownIcon } from './IconComponents';
import FileUpload from './FileUpload';

const ResumeOptimizer: React.FC<{ job: Job }> = ({ job }) => {
    const [resumeText, setResumeText] = useState('');
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [result, setResult] = useState<ResumeAnalysisResult | null>(null);
    const [copySuccess, setCopySuccess] = useState(false);
    const [showPasteMessage, setShowPasteMessage] = useState(false);

    const navigate = useNavigate();

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!resumeText) {
            setError('Please paste your resume text to analyze.');
            return;
        }
        setIsLoading(true);
        setError(null);
        setResult(null);
        try {
            const jobDescriptionText = `
                Job Title: ${job.title}
                Company: ${job.companyName}
                Location: ${job.location}
                Required Experience: ${job.experience}
                Required Skills: ${job.skills.join(', ')}
                Job Description: ${job.description}
            `;
            const analysisResult = await analyzeResumeAgainstJobDescription(resumeText, jobDescriptionText);
            setResult(analysisResult);
        } catch (err) {
            console.error(err);
            setError('Failed to analyze resume. The AI service may be temporarily unavailable.');
        } finally {
            setIsLoading(false);
        }
    };
    
    const handleCopy = () => {
        if (result?.ats_friendly_resume) {
            navigator.clipboard.writeText(result.ats_friendly_resume);
            setCopySuccess(true);
            setTimeout(() => setCopySuccess(false), 2000);
        }
    };

    const handleDownloadPdf = () => {
        if (result?.ats_friendly_resume) {
            navigate('/resume/print', { state: { resumeText: result.ats_friendly_resume, title: `Resume for ${job.title}` } });
        }
    };

    const handleDownloadDoc = () => {
        if (!result?.ats_friendly_resume) return;

        const header = "<html xmlns:o='urn:schemas-microsoft-com:office:office' "+
            "xmlns:w='urn:schemas-microsoft-com:office:word' "+
            "xmlns='http://www.w3.org/TR/REC-html40'>"+
            "<head><meta charset='utf-8'><title>Resume</title></head><body>";
        const footer = "</body></html>";
        const content = result.ats_friendly_resume.replace(/\n/g, '<br />');
        const sourceHTML = header + content + footer;

        const source = 'data:application/vnd.ms-word;charset=utf-8,' + encodeURIComponent(sourceHTML);
        const fileDownload = document.createElement("a");
        document.body.appendChild(fileDownload);
        fileDownload.href = source;
        fileDownload.download = 'optimized-resume.doc';
        fileDownload.click();
        document.body.removeChild(fileDownload);
    };

    const handleStartOver = () => {
        setResult(null);
        setResumeText('');
        setError(null);
        setShowPasteMessage(false);
    }

    return (
        <div className="mt-8 bg-indigo-50/50 p-6 rounded-xl border-2 border-dashed border-indigo-200">
            <div className="flex items-start space-x-4">
                <div className="flex-shrink-0 bg-indigo-100 p-3 rounded-full">
                    <SparklesIcon className="h-6 w-6 text-indigo-600" />
                </div>
                <div>
                    <h2 className="text-xl font-bold text-slate-800">Get an AI-Powered Edge</h2>
                    <p className="text-slate-600 mt-1">
                        Optimize your resume for the <strong>{job.title}</strong> role. Upload or paste your current resume to receive an improved, ATS-friendly version generated by AI.
                    </p>
                </div>
            </div>

            {!result && (
                <form onSubmit={handleSubmit} className="mt-6 space-y-4">
                    <div>
                        <label htmlFor="resume-optimizer-text" className="sr-only">Your Resume Text</label>
                        <FileUpload onFileSelect={() => setShowPasteMessage(true)} />
                        {showPasteMessage && (
                            <div className="mt-2 p-2 bg-indigo-50 border border-indigo-200 text-indigo-800 text-xs rounded-lg">
                                <strong>File selected!</strong> Now, please paste the text from your document into the text area below.
                            </div>
                        )}
                        <textarea
                            id="resume-optimizer-text"
                            value={resumeText}
                            onChange={(e) => setResumeText(e.target.value)}
                            rows={10}
                            className="mt-2 block w-full rounded-md border-slate-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
                            placeholder="Paste your full resume text here..."
                            required
                        />
                    </div>
                    {error && <p className="text-red-500 text-sm text-center">{error}</p>}
                    <button
                        type="submit"
                        disabled={isLoading}
                        className="w-full flex items-center justify-center py-3 px-4 border border-transparent rounded-lg shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 disabled:bg-indigo-300"
                    >
                        {isLoading ? <Spinner /> : <><SparklesIcon className="h-5 w-5 mr-2" /> Build My ATS-Friendly Resume</>}
                    </button>
                </form>
            )}
            
            {isLoading && (
                <div className="text-center mt-6">
                    <Spinner />
                    <p className="mt-3 text-slate-600 font-medium">Our AI is crafting your optimized resume...</p>
                    <p className="text-sm text-slate-500">This can take a few moments.</p>
                </div>
            )}

            {result && (
                <div className="mt-8 animate-fade-in space-y-6 border-t-2 border-dashed border-indigo-200 pt-6">
                    <div>
                        <h3 className="text-xl font-bold text-slate-800 text-center">Optimization Complete!</h3>
                    </div>
                    
                    {(() => {
                        const scoreColor = result.score >= 75 ? 'text-green-500' : result.score >= 50 ? 'text-yellow-500' : 'text-red-500';
                        return (
                             <div className={`text-center py-4 rounded-lg bg-white border`}>
                                <div className={`text-5xl font-bold ${scoreColor}`}>{result.score}<span className="text-2xl">%</span></div>
                                <p className="text-md font-semibold text-slate-600 mt-1">New ATS Compatibility Score</p>
                            </div>
                        )
                    })()}
                   
                    <div className="text-center bg-white p-4 rounded-lg border">
                        <h4 className="font-semibold text-slate-700 mb-1">AI Summary</h4>
                        <p className="text-slate-600 text-sm italic">"{result.summary}"</p>
                    </div>

                    <div>
                        <h4 className="font-semibold text-slate-700 mb-3">Your AI-Optimized Resume:</h4>
                        <div className="relative">
                             <pre className="text-slate-700 whitespace-pre-wrap font-sans text-sm bg-white p-4 rounded-md border border-slate-200 max-h-[50vh] overflow-y-auto">
                                {result.ats_friendly_resume}
                            </pre>
                            <button 
                                onClick={handleCopy}
                                className="absolute top-2 right-2 flex items-center bg-slate-100 hover:bg-slate-200 text-slate-700 text-xs font-semibold py-1 px-2 rounded-md transition-colors"
                            >
                                <DocumentDuplicateIcon className="h-4 w-4 mr-1.5" />
                                {copySuccess ? 'Copied!' : 'Copy'}
                            </button>
                        </div>
                    </div>
                     <div className="flex flex-col sm:flex-row gap-3">
                        <button onClick={handleDownloadPdf} className="flex-1 flex items-center justify-center bg-red-500 text-white font-semibold py-2 px-4 rounded-lg hover:bg-red-600 transition-all shadow-sm">
                           <PrinterIcon className="h-5 w-5 mr-2" /> Download as PDF
                        </button>
                        <button onClick={handleDownloadDoc} className="flex-1 flex items-center justify-center bg-blue-500 text-white font-semibold py-2 px-4 rounded-lg hover:bg-blue-600 transition-all shadow-sm">
                            <DocumentArrowDownIcon className="h-5 w-5 mr-2" /> Download as Word
                        </button>
                    </div>
                     <div className="text-center">
                        <button onClick={handleStartOver} className="text-indigo-600 hover:underline font-medium text-sm">
                            Start Over
                        </button>
                    </div>
                </div>
            )}
        </div>
    );
};

export default ResumeOptimizer;